name: Web Scraper

on:
  workflow_dispatch:  # Allows manual triggering of the workflow from GitHub

jobs:
  scrape_content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Or any version compatible with your PHP code

      - name: Install Dependencies
        run: composer require guzzlehttp/guzzle symfony/dom-crawler symfony/css-selector

      - name: Run PHP Scraper Script
        run: |
          php scraper.php > scrap.html
        shell: bash

      - name: Commit and Push scrap.html
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add scrap.html
          git commit -m "Add scraped content to scrap.html"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
